model_path: "<your model path>"       
device_map: "auto"                                  
dtype: "auto"
training_stage: "sft"

max_new_tokens: 512                                 
system_prompt: null
enable_history: false

do_sample: true
temperature: null                                  
top_k: null                                         
top_p: null                                         
repetition_penalty: null                                    